### ISSUE TITLE
syntax error, unexpected '...' (T_ELLIPSIS), expecting ']'

### ISSUE THREAD

**Issue by vaughn-taylor** [jorenvanhee/craft-template-guard#10]
Everything is working properly on my local environment, however I receive this error when the plugin is deployed my remote dev server. This error shows when I visit a protected area (eg. /blog/my-blog-post):

<img width="857" alt="Screen Shot 2022-04-20 at 12 50 57 PM" src="https://user-images.githubusercontent.com/2078376/164292206-9e597a0e-8a9c-47e1-8d0b-e18662e78e6a.png">

I'm using Craft CMS 3.7.37

**Comment by jorenvanhee** [comment]
I guess that your dev server runs an older ([unsupported](https://www.php.net/supported-versions.php)) version of php. PHP versions starting from 7.4 should support the `...` syntax.

**Comment by vaughn-taylor** [comment]
@jorenvanhee thanks for the quick response. That makes sense.
