### ISSUE TITLE
How to make a login page?

### ISSUE THREAD

**Issue by only1pulcinellacasarina** [jorenvanhee/craft-template-guard#11]
Just installed the Template Guard plug in but the documentation seems to be missing something.

It describes how to force a template to check whether you're logged in, but nothing about how to create that login page.

I'm guessing I need to create a template at: templates/template-guard/login
An example login page code would be helpful.
I tried using the login.twig - assuming that that might work, but I just gives me an internal server error page

**Comment by jorenvanhee** [comment]
I guess you've set the custom template configuration option as shown in [the readme](https://github.com/jorenvanhee/craft-template-guard#configuration)?

Does the plugin work when you leave the template option empty? Because there's a default login template in the plugin.

If you still get an error, please let me know the error, your php version, craft version and installed plugin version.

**Comment by only1pulcinellacasarina** [comment]
Thanks

I’ve tried that and am still getting an error:
https://inspirelondon.org/live-stream



Jonathan Spybey
***@***.***

**Comment by jorenvanhee** [comment]
Do you have a template in `templates/template-guard/login`? I think craft is still loading that template since the folder structure matches the url pattern ("template-guard/login").

**Comment by only1pulcinellacasarina** [comment]
Thanks

It’s moved on a bit, but not there yet:
https://inspirelondon.org/live-stream
Redirects to:
https://inspirelondon.org/template-guard/login?ref=https%3A//inspirelondon.org/live-stream

I’ve deliberately made the template for live-stream very simple to test it:



{% do craft.templateGuard.protect(['passwords1', 'passwords2']) %}
		
<!DOCTYPE html>
<html>
<body><div class="grid-container">
	
	
	<div class="cell small-12 side-margin-smallNOT">
            <section id="heading">
                <h1>Livestream Login</h1>
            </section>
	 </div>
			
</div>

</body>
</html>


The two weird things are:
The redirect link above goes to https%3A// instead of https:// (though it doesn’t make a difference if I change the URL
The page it redirects to is calling a different template. I suspect it’s the 404 template.

There’s perhaps other things also that you might notice.

Jonathan Spybey
***@***.***

**Comment by jorenvanhee** [comment]
The error originates from `_layouts/main.html` > `_includes/_meta.html`. Which probably means your still using a custom template, which is fine, but the error is not coming from the plugin.

I see that the `_meta` template expects an `entry` variable. There is no `entry` available on the login page, so it makes sense that it throws an error there. You could do a check to make sure `entry` exists before accessing the object.

**Comment by jorenvanhee** [comment]
I will close this for now since it doesn't seem to be an issue with the plugin.
