### ISSUE TITLE
Cookie Expiration Length Configuration

### ISSUE THREAD

**Issue by MikeMcChillin** [jorenvanhee/craft-template-guard#12]
Would it be possible to add a `cookieExpirationLength` variable to the config file to set a custom expiration length, rather than the current unconfigurable default of 1 hour?

Also wondering if
```
    const MAX_ATTEMPTS = 5;
    const MAX_ATTEMPTS_PERIOD_IN_SECONDS = 300;
```
could also be configurable.

**Comment by jorenvanhee** [comment]
That would be a good addition, I'll see if I can get it done this week :)
