### ISSUE TITLE
Logout option

### ISSUE THREAD

**Issue by bartrylant** [jorenvanhee/craft-template-guard#14]
Would it be possible to also make a logout option? Or can it be as easy as just deleting the set cookie?

**Comment by jorenvanhee** [comment]
Deleting the cookie will indeed do the job.

There's one caveat though: if you use multiple "guards", the user will be logged out of all of them.

I could add a better logout feature, but maybe deleting the cookie is good enough for your use case. Let me know!

**Comment by jorenvanhee** [comment]
Added in the latest release.
