### ISSUE TITLE
Access `entry` variable of requested page on login page?

### ISSUE THREAD

**Issue by proimage** [jorenvanhee/craft-template-guard#16]
On the login page, is there a way to access what would have been the `entry` variable of the requested page?

I've got a couple of reasons for wanting to do so:

- The site has automatic "Edit Entry" utility links on the frontend for logged-in users; it would be nice if the login page could show the "Edit Entry" link for the requested page: 
![image](https://github.com/jorenvanhee/craft-template-guard/assets/1027523/4a43033a-25e3-4860-a612-f9912746f751)
- I'm also thinking it might be useful to display the title of the requested page on the login screen, for reference.

**Comment by jorenvanhee** [comment]
This is currently not possible. What you could maybe do is use the reference in the url to the original page `craft.app.request.getParam('ref')`, extract the `slug` from that somehow and fetch an entry by slug in the template.

In the future I could maybe allow you to add more params to the url (besides `ref`). That would allow you to pass the entry id, and then fetch it on the login page. But currently, the login page does not have any notion of the protected entry, except for the url it should try to login on.

**Comment by proimage** [comment]
Ok, no biggie, thanks for letting me know.
