### ISSUE TITLE
(Feature Request) - Password array & Access count

### ISSUE THREAD

**Issue by vonscriptor** [jorenvanhee/craft-template-guard#2]
Please let me know your thoughts and the possibilities of adding in these features:

1. Allow an array of passwords to be used rather than just 1 per entry.
2. Store the number of times a password protected entry has been successfully accessed.
- Additionally if # 1 is implemented then make it specific to which password(s).
- Display this information in the admin.

The idea behind these features are to help identify if an allowed visitor has accessed the page(s) and additionally be able to have more specific identifiers by supporting multiple passwords.

I.e. The passwords for an entry could be as simple as a list of people's/company names or email addresses (strings). Security is less of a concern in this example, but seeing who accessed the page would be informative.

**Comment by jorenvanhee** [comment]
Hi, thanks for your feedback!

I can see the value in having multiple passwords to protect an entry, and can definitely look into this. This is something I could implement quickly.

I can also see why you'd want the second feature. In theory it should be possible. I'm already keeping track of failed login attempts. I could add the successful attempts as well. I would have to make sure that passwords are not being stored for failed attempts. Just in case someone tries to enter one of their own "real" passwords. This feature would take some more time to complete.

**Comment by vonscriptor** [comment]
Hi Joren, thanks for your thoughts on these features. I think they'd be very useful for people.

For the second feature, storing access logs (pass, fail, date+time) for each entry and its password(s) would you imagine this being visible in the admin in a plugin section view? That would be preferred so that CMS users are able to easily view that data. An example would be:

---
_**CMS Admin > Craft Template Guard >**_

> **Entry Name 1**
> 
> 1. **paSsWOrd1** (3 pass, 1 fail)
> ▾ Hide Log
> - PASS: 03-17-2022 11:57:06pm EST
> - PASS: 03-17-2022 8:19:53pm PST
> - PASS: 03-15-2022 3:14:19pm EST
> - FAIL: 03-15-2022 3:14:08pm EST
> 
> **Entry Name 2**
> 
> 1. **email@address.com** (5 pass, 0 fail)
> ▸ Show Log
> 
> 2. **another@email.com** (2 pass, 0 fail)
> ▸ Show Log
> 
> …

---

Would you have a timeframe you could consider to implement these changes? This would let me know if I should look into different solutions.

Thanks!

**Comment by jorenvanhee** [comment]
I just pushed the password array feature to a separate branch. It is not released yet but you should be able to test it.

For the second feature, I unfortunately can not give you any guarantees regarding the timeframe (since this is something I do on the side). Would it work for you if I start with storing the attempts in the database? You could then query the database yourself and display it to your users with a custom craft module. I could add something similar to the plugin later on.

**Comment by vonscriptor** [comment]
Thank you, I appreciate you taking the time to add that. I’m excited to take a look!

For the second feature, if you are storing them (per entry and each password w/passes and fails) could you make it accessible from a variable that I could get in Twig? That way I could do something like logged in users with permission can see that info displayed on the page.

**Comment by jorenvanhee** [comment]
This is not something that I would make publicly accessible through a variable. I think a simple controller (in a module) is better suited for the job. The plugin has an ActiveRecord record class `jorenvanhee\templateguard\records\LoginAttempt`. This record class is made for querying data.

I'm not sure how familiar you are with custom craft modules and ActiveRecord, but I could give you some guidance to get you started :)
