### ISSUE TITLE
XSS-vulnerability

### ISSUE THREAD

**Issue by boboldehampsink** [jorenvanhee/craft-template-guard#21]
Deze plugin bevat een zogenaamde “Cross Site Scripting (XSS) vulnerability”.
Onderstaande links spreken voor zich:

- /template-guard/login?ref=javascript:alert(0)
- /template-guard/login?ref=https://httpbin.org/post

Het is mogelijk om arbitraire javascript te injecteren (zie bovenste link). Het is ook mogelijk om de post-actie te veranderen (zie onderste link), waardoor het wachtwoord naar een ander domein wordt verzonden.

**Comment by jorenvanhee** [comment]
Thanks for reporting and the suggested fix. I just merged #23 which fixes the issue.
