### ISSUE TITLE
Feature request: override lockout for too many requests

### ISSUE THREAD

**Issue by KatieMFritz** [jorenvanhee/craft-template-guard#6]
First off, thanks for this plugin! It's exactly what I need.

I'm using Cypress to write integration tests for some password protected entries. When I try to log in with my browser, I'm getting the error `Too many attempts, try again later.`. 

Is there somewhere I can override this? Even better if I could override it per environment (we'll hit the authentication page much harder on local environments while testing than in production).

**Comment by jorenvanhee** [comment]
This is not configurable at the moment but definitely something I can add. I'll keep you posted!

In the mean time you could update the hardcoded `MAX_ATTEMPTS` value in [the plugin codebase](https://github.com/jorenvanhee/craft-template-guard/blob/main/src/services/LoginAttemptService.php#L14).

**Comment by jorenvanhee** [comment]
I made a pr (#9) that adds configurability of the max attempts. You could already try to use this branch before I release it.

**Comment by jorenvanhee** [comment]
This is now available in version 1.2.0.
