### ISSUE TITLE
'Back' triggers form resubmission

### ISSUE THREAD

**Issue by nathanaeljames** [jorenvanhee/craft-template-guard#7]
After entering the password successfully and being successfully redirected to the protected page, clicking back will result in website visitors being asked to enter their password again or asking for confirmation of form resubmission. This did not seem to be the case with past releases, noticed it after updating the plugin

**Comment by jorenvanhee** [comment]
This has always been the case, but annoyed me a little as well. I'll see what I can do :)

**Comment by jorenvanhee** [comment]
I gave it a try and didn't see how I could prevent this behaviour. Feel free to do suggestions, but I will close this for now.
