### ISSUE TITLE
Deprecation Error

### ISSUE THREAD

**Issue by vaughn-taylor** [jorenvanhee/craft-template-guard#8]
You have a deprecation error in /var/www/html/vendor/jorenvanhee/craft-template-guard/src/templates/login.twig:19

craft.request.getParam() has been deprecated. Use craft.app.request.getParam() instead.

**Comment by jorenvanhee** [comment]
I recently tagged a release `2.0.0-beta.1` ready for craft 4. That version of the plugin uses `craft.app.request`, so this will not cause any problems in the future. Thanks for bringing it to my attention!
